/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBanner: typeof import('./src/components/AppBanner.vue')['default']
    AppFeedback: typeof import('./src/components/AppFeedback.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppSection: typeof import('./src/components/AppSection.vue')['default']
    ContentWrapper: typeof import('./src/components/ContentWrapper.vue')['default']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ExternalLink: typeof import('./src/components/ExternalLink.vue')['default']
    FilterCheckbox: typeof import('./src/components/filter/FilterCheckbox.vue')['default']
    FilterHeader: typeof import('./src/components/filter/FilterHeader.vue')['default']
    FilterRadio: typeof import('./src/components/filter/FilterRadio.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    OCardItem: typeof import('./src/components/OCardItem.vue')['default']
    OCodeCopy: typeof import('./src/components/OCodeCopy.vue')['default']
    OTableItemNew: typeof import('./src/components/OTableItemNew.vue')['default']
    ResultNotFound: typeof import('./src/components/ResultNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/search/SearchFilter.vue')['default']
    SearchRecommend: typeof import('./src/components/search/SearchRecommend.vue')['default']
    SearchTab: typeof import('./src/components/search/SearchTab.vue')['default']
  }
}
