/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBanner: typeof import('./src/components/AppBanner.vue')['default']
    AppBreadcrumb: typeof import('./src/components/AppBreadcrumb.vue')['default']
    AppFeedback: typeof import('./src/components/AppFeedback.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    AppSection: typeof import('./src/components/AppSection.vue')['default']
    AppTableToggle: typeof import('./src/components/AppTableToggle.vue')['default']
    ContentWrapper: typeof import('./src/components/ContentWrapper.vue')['default']
    DetailAside: typeof import('./src/components/DetailAside.vue')['default']
    DetailHeader: typeof import('./src/components/DetailHeader.vue')['default']
    DetailSkeleton: typeof import('./src/components/skeleton/DetailSkeleton.vue')['default']
    ExternalLink: typeof import('./src/components/ExternalLink.vue')['default']
    FilterCheckbox: typeof import('./src/components/filter/FilterCheckbox.vue')['default']
    FilterHeader: typeof import('./src/components/filter/FilterHeader.vue')['default']
    FilterItemSkeleton: typeof import('./src/components/skeleton/FilterItemSkeleton.vue')['default']
    FilterRadio: typeof import('./src/components/filter/FilterRadio.vue')['default']
    HeaderNav: typeof import('./src/components/HeaderNav.vue')['default']
    HomeSkeleton: typeof import('./src/components/skeleton/HomeSkeleton.vue')['default']
    OCardItem: typeof import('./src/components/OCardItem.vue')['default']
    OCardItemSkeleton: typeof import('./src/components/skeleton/OCardItemSkeleton.vue')['default']
    OCodeCopy: typeof import('./src/components/OCodeCopy.vue')['default']
    OTableItemNew: typeof import('./src/components/OTableItemNew.vue')['default']
    ResultNotApp: typeof import('./src/components/ResultNotApp.vue')['default']
    ResultNotFound: typeof import('./src/components/ResultNotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchFilter: typeof import('./src/components/search/SearchFilter.vue')['default']
    SearchRecommend: typeof import('./src/components/search/SearchRecommend.vue')['default']
    SearchTab: typeof import('./src/components/search/SearchTab.vue')['default']
  }
}
